#include "GardensnakeApp.h"
#include "Moose.h"
#include "AppFactory.h"

InputParameters
GardensnakeApp::validParams()
{
  InputParameters params = MooseApp::validParams();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

GardensnakeApp::GardensnakeApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  GardensnakeApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  GardensnakeApp::associateSyntax(_syntax, _action_factory);
}

GardensnakeApp::~GardensnakeApp()
{
}

extern "C" void GardensnakeApp__registerApps() { GardensnakeApp::registerApps(); }
void
GardensnakeApp::registerApps()
{
  registerApp(GardensnakeApp);
}

void
GardensnakeApp::registerObjects(Factory & factory)
{
}

void
GardensnakeApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
